### ISSUE TITLE
backport fix of GeckoDiffOutputBuilder

### ISSUE THREAD

**Issue by SpacePossum** [PHP-CS-Fixer/diff#6]
as done/released @ v1.1

**Comment by keradus** [comment]
is this fix already applied for diff v3 ?

**Comment by SpacePossum** [comment]
it is, with diff 3 the (patched) Gecko one is added into there so it can be dropped altogether

**Comment by keradus** [comment]
so maybe no need for update, if we have https://github.com/PHP-CS-Fixer/diff/pull/7 now ?

**Comment by SpacePossum** [comment]
indeed, good call, with 7 this issue is no longer relevant.
