### ISSUE TITLE
1.2.0 is not on packagist

### ISSUE THREAD

**Issue by nesl247** [PHP-CS-Fixer/diff#8]
This is causing me to be unable to run `composer update`.

```
Problem 1
    - Installation request for friendsofphp/php-cs-fixer ^2.10 -> satisfiable by friendsofphp/php-cs-fixer[v2.10.0].
    - friendsofphp/php-cs-fixer v2.10.0 requires php-cs-fixer/diff ^1.2 -> no matching package found.
```

My guess is the webhook didn't get added for auto-updating.

**Comment by jaydiablo** [comment]
Seems like it was pulled from packagist.  php-cs-fixer has depended on that version since 2.8.0 which was released in November of 2017.  We've had plenty of apps using php-cs-fixer 2.10.0 over the past week or so install just fine, but now they won't if the vendor dir is wiped.

**Comment by SpacePossum** [comment]
hitting `update` on `https://packagist.org/packages/php-cs-fixer/diff` doesn't help either, cc @keradus , could you give it a try?

**Comment by SpacePossum** [comment]
update: 1.2.1 is now listed on packalist, 1.2.0 still isn't, however this should fix a lot of broken installs while we try to figure out what happened to 1.2.0

thanks for reporting people!

**Comment by keradus** [comment]
I must say I have no clue, especially since 1.2.0 was on packagist (if it wouldn't, we would not be able to install PHP CS Fixer for a long time already).
Update not working, even recreating the tag didn't bring it back to packagist.
sadly, don't see anything we can do on top of having 1.2.1

**Comment by SpacePossum** [comment]
thanks for checking and trying!

**Comment by julienfalque** [comment]
For information, version 1.2.0 is available again: https://packagist.org/packages/php-cs-fixer/diff#v1.2.0

```console
$ composer require --dev php-cs-fixer/diff:1.2.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing php-cs-fixer/diff (v1.2.0): Loading from cache
```
